server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/JeeCoding?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
 #\u8FD9\u4E2A\u914D\u7F6E\u7528\u6765\u6307\u5B9Abean\u5728\u54EA\u4E2A\u5305\u91CC\uFF0C\u907F\u514D\u5B58\u5728\u540C\u540Dclass\u65F6\u627E\u4E0D\u5230bean
  type-aliases-package: com.huzh.springbootmybatisxml.model
  ##\u68C0\u67E5 mbg \u914D\u7F6E\u662F\u5426\u5B58\u5728\uFF0C\u4E00\u822C\u547D\u540D\u4E3A mbg-config.xml
  check-config-location: true
  ##\u914D\u7F6E\u6587\u4EF6\u4F4D\u7F6E
  config-location: classpath:mbg/mybatis-config.xml
  ## dao xml \u6587\u4EF6\u5730\u5740
  mapper-locations:
    - classpath:mapper/*Mapper.xml
#    - classpath*:com/**/mbg/*.xml